#!/bin/sh

# general config

. /etc/conf.d/nsrv
. /etc/rc.conf
. /etc/rc.d/functions

# global varaibles
declare PIDS
FILES=$(find $VHOSTS -name \*\.conf)

case "$1" in
  start)
    stat_busy "Starting NodeJS Development Servers"
    for file in $FILES
    do
      . $file

      if [ $LANGUAGE = 'javascript' ] && [ $PLATFORM = 'nodejs' ] ; then
        node $ROOT/$SCRIPT $ADDR $PORT &
        pidof node -s >> $PIDFILE
      else
        echo "Unknow language or flamework."
      fi

    done

    if [ -e $PIDFILE ] ; then
      add_daemon nsrv
      stat_done
    else
      stat_fail
    fi
    ;; 
  stop)
    stat_busy "Stopping CGI Server"
    [ -e /var/run/daemons/nsrv ] && [ -e $PIDFILE ]
    PIDS=`cat $PIDFILE`
    for pid in $PIDS
    do
      kill  $pid &> /dev/null
      #killall gunicorn_django
    done

    if [ $? -ne 0 ] ; then
      stat_fail
    else
      rm_daemon nsrv
      rm $PIDFILE
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|}"  
esac
