#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/lircd.conf

PID=$(pidof -o %PPID /usr/sbin/lircd)
LIRCD_SYMLINKFILE=/dev/lircd
LIRCD_SOCKET=/run/lirc/lircd
case "$1" in
    start)
        stat_busy "Starting LIRC Daemon"
        if [ ! -d /run/lirc ]; then
          mkdir -p /run/lirc
        fi
        [ -n "$LIRC_DRIVER" ] && LIRC_EXTRAOPTS="-H $LIRC_DRIVER $LIRC_EXTRAOPTS"
        [ -z "$PID" ] && 
        if [ -n "$LIRC_DEVICE0" ] && [ -n "$LIRC_DEVICE1" ] ; then
            /usr/sbin/lircd -d "$LIRC_DEVICE0" $LIRC_EXTRAOPTS $REMOTE_CONFIG_FILE --pidfile=/run/lirc/lircd0.pid --output=/run/lirc/lircd0  --listen
            /usr/sbin/lircd -d "$LIRC_DEVICE1" $LIRC_EXTRAOPTS $REMOTE_CONFIG_FILE --pidfile=/run/lirc/lircd.pid  --output=/run/lirc/lircd   --connect=localhost:8765
            ln -s "$LIRCD_SOCKET" "$LIRCD_SYMLINKFILE"
        else
            /usr/sbin/lircd $LIRC_EXTRAOPTS $REMOTE_CONFIG_FILE --pidfile=/run/lirc/lircd0.pid  --output=/run/lirc/lircd0 --listen
            /usr/sbin/lircd $LIRC_EXTRAOPTS $REMOTE_CONFIG_FILE --pidfile=/run/lirc/lircd.pid   --output=/run/lirc/lircd  --connect=localhost:8765
            ln -s "$LIRCD_SOCKET" "$LIRCD_SYMLINKFILE" 
        fi
        if [ $? -gt 0 ]; then
            stat_fail
        else
            add_daemon lircd
            stat_done
        fi
        ;;
    stop)
        stat_busy "Stopping LIRC Daemon"
        [ ! -z "$PID" ] && kill $PID &> /dev/null
        if [ $? -gt 0 ]; then
            stat_fail
        else
            rm_daemon lircd
            rm -f $LIRCD_SYMLINKFILE
            stat_done
        fi
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"
esac
exit 0
