#!/bin/sh

# general config

. /etc/conf.d/xode
. /etc/rc.conf
. /etc/rc.d/functions

# global varaibles
	declare PIDS
FILES=$(find $VHOSTS -name \*\.conf)

	case "$1" in
	start)
	stat_busy "Starting Nodejs Development Servers"
	for file in $FILES
	do
	. $file

	if [ $LANGUAGE = 'javascript' ] && [ $PLATFORM = 'nodejs' ] ; then
	cd $ROOT
        node $SCRIPT $ADDR $PORT > /dev/null&
	pidof node -s >> $PIDFILE
	else
	echo "Unknow language or flamework."
	fi

	done

	if [ -e $PIDFILE ] ; then
	add_daemon xode
	stat_done
	else
	stat_fail
	fi
	;; 
	stop)
	stat_busy "Stopping Nodejs Development Servers"
	[ -e /var/run/daemons/xode ] && [ -e $PIDFILE ]
	PIDS=`cat $PIDFILE`
	for pid in $PIDS
	do
	kill  $pid &> /dev/null
	done

	if [ $? -ne 0 ] ; then
	stat_fail
	else
	rm_daemon xode
	rm $PIDFILE
	stat_done
	fi
	;;
	restart)
	$0 stop
	sleep 1
	$0 start
	;;
	*)
	echo "Usage: $0 {start|stop|restart|}"  
	esac
