#!/bin/bash

# general config

TERMSEED_DIR="/home/kuno/harbour/TermSeed"

#. /etc/conf.d/termseed
. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting TermSeed Daemon"
    if [ -s /var/run/termseed-daemon.pid ]; then
      stat_fail
      # probably ;)
      stat_busy "TermSeed Daemon is already running"
      stat_die
    fi
    cd "${TERMSEED_DIR}"/Node && /usr/bin/node nodekit.js 2>/dev/null &
    if [ $? -ne 0 ]; then
      stat_fail
    else
      add_daemon termseed-daemon
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping TermSeed Daemon"
    kill -QUIT `cat /var/run/termseed-daemon.pid` &>/dev/null
    if [ $? -ne 0 ]; then
      stat_fail
    else
      rm_daemon termseed
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac    
