#!/bin/sh

# general config

. /etc/conf.d/crane
. /etc/rc.conf
. /etc/rc.d/functions

# global varaibles
FOLDERS=$(ls $REPO_DIR)

case "$1" in
  pull)
    stat_busy "Pull data from remote server"
    for folder in $FOLDERS
    do
      cd $REPO_DIR/$folder || return 1
      stat_busy "Working in repository $folder"
      if [ -d $REPO_DIR/$folder/.git ]; then
        if [ -d $REPO_DIR/$folder/.git/refs/remotes ]; then
          git pull
        fi
      elif [ -d $REPO_DIR/$folder/.hg ]; then
        hg pull && hg update
      else
        stat_busy "$folder is not a repository folder"
      fi
      chown -R kuno:root $REPO_DIR/$folder || return 1
    done
    ;;
  push)
    stat_busy "Push data to remote server"
    for folder in $FOLDERS; do
      stat_busy "Working in repository $folder"
      cd $REPO_DIR/$folder || return 1
      if [ -d $REPO_DIR/$folder/.git ]; then
        if [ -d $REPO_DIR/$folder/.git/refs/remotes ]; then
          git push
        fi 
      elif [ -d $REPO_DIR/$folder/.hg ]; then
        hg push
      else
        stat_busy "$folder is not a repository folder"
      fi
      chown -R kuno:root $REPO_DIR/$folder || return 1 
    done
    ;;
  start)
    $0 push
    sleep 1
    $0 pull
    ;;
  *)
    echo "Usage: $0 {pull|push|start}"
esac
